name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [master]
    paths-ignore:
      - "assets/metrics/**"

permissions:
  contents: write

jobs:
  # Languages
  metrics-languages:
    name: Languages
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: percentage
          plugin_languages_limit: 8
          plugin_languages_sections: most-used

  # Isometric commit calendar
  metrics-isocalendar:
    name: Isometric Calendar
    needs: metrics-languages
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/isocalendar.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

  # Coding habits
  metrics-habits:
    name: Habits
    needs: metrics-isocalendar
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_trim: yes

  # Achievements
  metrics-achievements:
    name: Achievements
    needs: metrics-habits
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/achievements.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes

  # GitHub activity
  metrics-activity:
    name: Activity
    needs: metrics-achievements
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity
          plugin_lines: yes

  # Anilist characters
  metrics-anilist:
    name: Anilist Characters
    needs: metrics-activity
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: assets/metrics/anilist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_anilist: yes
          plugin_anilist_user: fenyyei
          plugin_anilist_medias: anime
          plugin_anilist_sections: characters
          plugin_anilist_limit_characters: 100
          plugin_anilist_shuffle: no